### ISSUE TITLE
Error during file copying

### ISSUE THREAD

**Issue by egges** [elwin013/parcel-plugin-static-files-copy#47]
After updating to the latest version (2.3.4) I now get an error when building my project:

```
(node:142) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, copyfile '/opt/atlassian/pipelines/agent/build/assets/background_login.jpg' -> '/opt/atlassian/pipelines/agent/build/dist/client/assets/background_login.jpg'
    at Object.copyFileSync (fs.js:1807:3)
    at copy (/opt/atlassian/pipelines/agent/build/node_modules/parcel-plugin-static-files-copy/index.js:128:32)
    at /opt/atlassian/pipelines/agent/build/node_modules/parcel-plugin-static-files-copy/index.js:99:25
    at Array.forEach (<anonymous>)
    at recurse (/opt/atlassian/pipelines/agent/build/node_modules/parcel-plugin-static-files-copy/index.js:90:41)
    at recurseSync (/opt/atlassian/pipelines/agent/build/node_modules/parcel-plugin-static-files-copy/index.js:105:13)
    at copyDir (/opt/atlassian/pipelines/agent/build/node_modules/parcel-plugin-static-files-copy/index.js:137:17)
    at Bundler.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/parcel-plugin-static-files-copy/index.js:163:17)
(node:142) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:142) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The settings in my package.json file are:
```
"staticFiles": {
        "staticPath": [
            {
                "staticPath": "assets",
                "staticOutDir": "assets"
            }
        ],
        "watcherGlob": "**"
    }
```

Reverting to version 2.3.1 solves the issue.

**Comment by elwin013** [comment]
Hello @egges!

Could you tell me what command (what parameters/options) do you use to run parcel?

**Comment by egges** [comment]
Sure. This is the command I run (I build a separate client and server for SSR):

parcel build src/client/index.tsx -d dist/client

**Comment by elwin013** [comment]
I was able to reproduce bug and fixed it. Version 2.3.5 will/should contain fix :-)

Thank you for reporting! :-)

**Comment by egges** [comment]
Thanks!
