### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir ..../build

### ISSUE THREAD

**Issue by jindev** [elwin013/parcel-plugin-static-files-copy#50]
after version up to 2.4.1. it keeps returning an error.

```
PARCEL_WORKERS=1 NODE_ENV=production parcel build myapp/src/index.html --out-dir build
```

```

build/assets/images/favicon/site.webmanifest               117 B       65ms
(node:26) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir '/myapp/build'
    at Object.mkdirSync (fs.js:729:3)
    at processStaticFiles (/silver-admin-web/packages/silver-admin-frontend/node_modules/parcel-plugin-static-files-copy/index.js:157:20)
    at Bundler.bundler.on (/silver-admin-web/packages/silver-admin-frontend/node_modules/parcel-plugin-static-files-copy/index.js:167:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:26) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by jindev** [comment]
hi @elwin013 
using macOS: 10.15.5

**Comment by elwin013** [comment]
@jindev FYI: should be fixed in 2.4.3 (as described in #49).
