### ISSUE TITLE
Error using multiple environments

### ISSUE THREAD

**Issue by ConteaHNL** [elwin013/parcel-plugin-static-files-copy#70]
Thank you for this amazing plugin.

When i use this setup everything works fine:
```
"scripts": {
    "build": "cross-env NODE_ENV=prod parcel build src/index.js --no-hmr -d ./wwwroot/dist",
    "watch": "cross-env NODE_ENV=dev parcel watch src/index.js --no-hmr -d ./wwwroot/dist"
  },
  "staticFiles": {
    "staticPath": [
      {
        "staticPath": "node_modules/jquery/dist/jquery.min.js",
        "env": "dev",
        "staticOutDir": "vendor"
      },
      {
        "staticPath": "node_modules/jquery/dist/jquery.min.js",
        "env": "prod",
        "staticOutDir": "vendor"
      }
    ]
  },
```

But when i use an array instead for staticPath (which works with only one environment) :

```
  "staticFiles": {
    "staticPath": [
      {
        "staticPath": [
          "node_modules/jquery/dist/jquery.min.js",
          "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js",
          "node_modules/bootstrap-select/dist/js/bootstrap-select.min.js",
          "node_modules/autonumeric/dist/autoNumeric.min.js",
          "node_modules/flatpickr/dist/flatpickr.min.js",
          "node_modules/moment/min/moment-with-locales.min.js",
          "node_modules/dropzone/dist/min/dropzone.min.js",
          "node_modules/datatables.net/js/jquery.dataTables.min.js",
          "node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js",
          "node_modules/datatables.net-buttons/js/dataTables.buttons.min.js",
          "node_modules/datatables.net-rowgroup-bs4/js/rowGroup.bootstrap4.min.js",
          "node_modules/moment/dist/moment.js",
          "node_modules/moment/dist/locale/da.js",
          "node_modules/popper.js/dist/popper.min.js",
          "node_modules/jzip/jzip.js",
          "node_modules/jquery-validation/dist/jquery.validate.min.js"
        ],
        "env": "dev",
        "staticOutDir": "vendor"
      },
      {
        "staticPath": [
          "node_modules/jquery/dist/jquery.min.js",
          "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js",
          "node_modules/bootstrap-select/dist/js/bootstrap-select.min.js",
          "node_modules/autonumeric/dist/autoNumeric.min.js",
          "node_modules/flatpickr/dist/flatpickr.min.js",
          "node_modules/moment/min/moment-with-locales.min.js",
          "node_modules/dropzone/dist/min/dropzone.min.js",
          "node_modules/datatables.net/js/jquery.dataTables.min.js",
          "node_modules/datatables.net-bs4/js/dataTables.bootstrap4.min.js",
          "node_modules/datatables.net-buttons/js/dataTables.buttons.min.js",
          "node_modules/datatables.net-rowgroup-bs4/js/rowGroup.bootstrap4.min.js",
          "node_modules/moment/dist/moment.js",
          "node_modules/moment/dist/locale/da.js",
          "node_modules/popper.js/dist/popper.min.js",
          "node_modules/jzip/jzip.js",
          "node_modules/jquery-validation/dist/jquery.validate.min.js"
        ],
        "env": "prod",
        "staticOutDir": "vendor"
      }
    ]
  },

```
i get the following error:

```

node:12232) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received an instance of Array   
    at validateString (internal/validators.js:120:11)
    at Object.join (path.js:375:7)
    at processStaticFiles (D:\code\RiskLogic\Risklogic\node_modules\parcel-plugin-static-files-copy\index.js:177:39)
    at Bundler.<anonymous> (D:\code\RiskLogic\Risklogic\node_modules\parcel-plugin-static-files-copy\index.js:195:13)
```

Running in VSCode on Windows 10 with Node.js version 12.19.0

**Comment by elwin013** [comment]
Hey ConteaHNL!

Please check out v2.6.0 and example in `examples/multiple-nested-config`. :-)
